### PR TITLE
Merge final release version 2.4 

### PR DESCRIPTION
**Pull request by tmelliott**

### CODE REVIEW

**Comment by tmelliott** [comment]
I'll try and get the CI checks to pass ...

**Comment by tmelliott** [comment]
@daniel-barnett merged some old changes from `master` so hopefully I haven't broken anything

**Comment by daniel-barnett** [comment]
Doesn't seem to have broken anything when I tried it!

**Comment by tmelliott** [comment]
Cool - I'm messing with the documentation on `dev`, so perhaps checkout onto a new branch to prevent too many conflicts while I try get the travis CI to pass.

Also, moving this PR to a release branch instead.

**Pull request closed without merging**
